
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CardProduct': typeof import("../components/CardProduct.vue")['default']
    'CardProductFlashsale': typeof import("../components/CardProductFlashsale.vue")['default']
    'CardProductHome': typeof import("../components/CardProductHome.vue")['default']
    'CardProductRecommend': typeof import("../components/CardProductRecommend.vue")['default']
    'CompareMac': typeof import("../components/CompareMac.vue")['default']
    'CompareiPhone': typeof import("../components/CompareiPhone.vue")['default']
    'CradProductAccessories': typeof import("../components/CradProductAccessories.vue")['default']
    'Profile': typeof import("../components/Profile.vue")['default']
    'ProfileAddressProduct': typeof import("../components/ProfileAddressProduct.vue")['default']
    'ProfileOrderList': typeof import("../components/ProfileOrderList.vue")['default']
    'ServiceShipping': typeof import("../components/ServiceShipping.vue")['default']
    'ServiceWarranty': typeof import("../components/ServiceWarranty.vue")['default']
    'SwiperProductCategory': typeof import("../components/SwiperProductCategory.vue")['default']
    'SwiperProductHome': typeof import("../components/SwiperProductHome.vue")['default']
    'SwiperProductSerie': typeof import("../components/SwiperProductSerie.vue")['default']
    'IconAccount': typeof import("../components/icon/Account.vue")['default']
    'IconAddressProduct': typeof import("../components/icon/AddressProduct.vue")['default']
    'IconArrowDown': typeof import("../components/icon/ArrowDown.vue")['default']
    'IconArrowLeft': typeof import("../components/icon/ArrowLeft.vue")['default']
    'IconArrowRight': typeof import("../components/icon/ArrowRight.vue")['default']
    'IconBorderActive': typeof import("../components/icon/BorderActive.vue")['default']
    'IconBoxalt': typeof import("../components/icon/Boxalt.vue")['default']
    'IconBoxconfirm': typeof import("../components/icon/Boxconfirm.vue")['default']
    'IconCalendar': typeof import("../components/icon/Calendar.vue")['default']
    'IconCart': typeof import("../components/icon/Cart.vue")['default']
    'IconCheckCalendar': typeof import("../components/icon/CheckCalendar.vue")['default']
    'IconClock': typeof import("../components/icon/Clock.vue")['default']
    'IconCoupon': typeof import("../components/icon/Coupon.vue")['default']
    'IconCreditcard': typeof import("../components/icon/Creditcard.vue")['default']
    'IconDocument': typeof import("../components/icon/Document.vue")['default']
    'IconDots': typeof import("../components/icon/Dots.vue")['default']
    'IconHamburgerMenu': typeof import("../components/icon/HamburgerMenu.vue")['default']
    'IconInfo': typeof import("../components/icon/Info.vue")['default']
    'IconInvoiceState': typeof import("../components/icon/InvoiceState.vue")['default']
    'IconLocation': typeof import("../components/icon/Location.vue")['default']
    'IconLogout': typeof import("../components/icon/Logout.vue")['default']
    'IconOrderList': typeof import("../components/icon/OrderList.vue")['default']
    'IconPackage': typeof import("../components/icon/Package.vue")['default']
    'IconPeopleLogin': typeof import("../components/icon/PeopleLogin.vue")['default']
    'IconPlusAdd': typeof import("../components/icon/PlusAdd.vue")['default']
    'IconQuotation': typeof import("../components/icon/Quotation.vue")['default']
    'IconReceipt': typeof import("../components/icon/Receipt.vue")['default']
    'IconScan': typeof import("../components/icon/Scan.vue")['default']
    'IconSearch': typeof import("../components/icon/Search.vue")['default']
    'IconShipping': typeof import("../components/icon/Shipping.vue")['default']
    'IconShippingFast': typeof import("../components/icon/ShippingFast.vue")['default']
    'IconShoppingFast': typeof import("../components/icon/ShoppingFast.vue")['default']
    'IconSocialApple': typeof import("../components/icon/SocialApple.vue")['default']
    'IconSocialApple2': typeof import("../components/icon/SocialApple2.vue")['default']
    'IconSocialFacebook': typeof import("../components/icon/SocialFacebook.vue")['default']
    'IconSocialFacebook2': typeof import("../components/icon/SocialFacebook2.vue")['default']
    'IconSocialGoogle': typeof import("../components/icon/SocialGoogle.vue")['default']
    'IconSocialGoogle2': typeof import("../components/icon/SocialGoogle2.vue")['default']
    'IconSocialLine': typeof import("../components/icon/SocialLine.vue")['default']
    'IconStatusBoxcheck': typeof import("../components/icon/StatusBoxcheck.vue")['default']
    'IconStatusLoading': typeof import("../components/icon/StatusLoading.vue")['default']
    'IconStatusShopFast': typeof import("../components/icon/StatusShopFast.vue")['default']
    'IconStatusTimedelete': typeof import("../components/icon/StatusTimedelete.vue")['default']
    'IconSuesccCheck': typeof import("../components/icon/SuesccCheck.vue")['default']
    'IconTaxBill': typeof import("../components/icon/TaxBill.vue")['default']
    'IconTrash': typeof import("../components/icon/Trash.vue")['default']
    'IconTruckFast': typeof import("../components/icon/TruckFast.vue")['default']
    'IconWarningInput': typeof import("../components/icon/WarningInput.vue")['default']
    'IconWarrantys': typeof import("../components/icon/Warrantys.vue")['default']
    'IconEyeHide': typeof import("../components/icon/eyeHide.vue")['default']
    'IconEyeShow': typeof import("../components/icon/eyeShow.vue")['default']
    'IconIPadProduct': typeof import("../components/icon/iPadProduct.vue")['default']
    'IconVisa': typeof import("../components/icon/visa.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Swiper': typeof import("../node_modules/swiper/swiper-vue")['Swiper']
    'SwiperSlide': typeof import("../node_modules/swiper/swiper-vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCardProduct': typeof import("../components/CardProduct.vue")['default']
    'LazyCardProductFlashsale': typeof import("../components/CardProductFlashsale.vue")['default']
    'LazyCardProductHome': typeof import("../components/CardProductHome.vue")['default']
    'LazyCardProductRecommend': typeof import("../components/CardProductRecommend.vue")['default']
    'LazyCompareMac': typeof import("../components/CompareMac.vue")['default']
    'LazyCompareiPhone': typeof import("../components/CompareiPhone.vue")['default']
    'LazyCradProductAccessories': typeof import("../components/CradProductAccessories.vue")['default']
    'LazyProfile': typeof import("../components/Profile.vue")['default']
    'LazyProfileAddressProduct': typeof import("../components/ProfileAddressProduct.vue")['default']
    'LazyProfileOrderList': typeof import("../components/ProfileOrderList.vue")['default']
    'LazyServiceShipping': typeof import("../components/ServiceShipping.vue")['default']
    'LazyServiceWarranty': typeof import("../components/ServiceWarranty.vue")['default']
    'LazySwiperProductCategory': typeof import("../components/SwiperProductCategory.vue")['default']
    'LazySwiperProductHome': typeof import("../components/SwiperProductHome.vue")['default']
    'LazySwiperProductSerie': typeof import("../components/SwiperProductSerie.vue")['default']
    'LazyIconAccount': typeof import("../components/icon/Account.vue")['default']
    'LazyIconAddressProduct': typeof import("../components/icon/AddressProduct.vue")['default']
    'LazyIconArrowDown': typeof import("../components/icon/ArrowDown.vue")['default']
    'LazyIconArrowLeft': typeof import("../components/icon/ArrowLeft.vue")['default']
    'LazyIconArrowRight': typeof import("../components/icon/ArrowRight.vue")['default']
    'LazyIconBorderActive': typeof import("../components/icon/BorderActive.vue")['default']
    'LazyIconBoxalt': typeof import("../components/icon/Boxalt.vue")['default']
    'LazyIconBoxconfirm': typeof import("../components/icon/Boxconfirm.vue")['default']
    'LazyIconCalendar': typeof import("../components/icon/Calendar.vue")['default']
    'LazyIconCart': typeof import("../components/icon/Cart.vue")['default']
    'LazyIconCheckCalendar': typeof import("../components/icon/CheckCalendar.vue")['default']
    'LazyIconClock': typeof import("../components/icon/Clock.vue")['default']
    'LazyIconCoupon': typeof import("../components/icon/Coupon.vue")['default']
    'LazyIconCreditcard': typeof import("../components/icon/Creditcard.vue")['default']
    'LazyIconDocument': typeof import("../components/icon/Document.vue")['default']
    'LazyIconDots': typeof import("../components/icon/Dots.vue")['default']
    'LazyIconHamburgerMenu': typeof import("../components/icon/HamburgerMenu.vue")['default']
    'LazyIconInfo': typeof import("../components/icon/Info.vue")['default']
    'LazyIconInvoiceState': typeof import("../components/icon/InvoiceState.vue")['default']
    'LazyIconLocation': typeof import("../components/icon/Location.vue")['default']
    'LazyIconLogout': typeof import("../components/icon/Logout.vue")['default']
    'LazyIconOrderList': typeof import("../components/icon/OrderList.vue")['default']
    'LazyIconPackage': typeof import("../components/icon/Package.vue")['default']
    'LazyIconPeopleLogin': typeof import("../components/icon/PeopleLogin.vue")['default']
    'LazyIconPlusAdd': typeof import("../components/icon/PlusAdd.vue")['default']
    'LazyIconQuotation': typeof import("../components/icon/Quotation.vue")['default']
    'LazyIconReceipt': typeof import("../components/icon/Receipt.vue")['default']
    'LazyIconScan': typeof import("../components/icon/Scan.vue")['default']
    'LazyIconSearch': typeof import("../components/icon/Search.vue")['default']
    'LazyIconShipping': typeof import("../components/icon/Shipping.vue")['default']
    'LazyIconShippingFast': typeof import("../components/icon/ShippingFast.vue")['default']
    'LazyIconShoppingFast': typeof import("../components/icon/ShoppingFast.vue")['default']
    'LazyIconSocialApple': typeof import("../components/icon/SocialApple.vue")['default']
    'LazyIconSocialApple2': typeof import("../components/icon/SocialApple2.vue")['default']
    'LazyIconSocialFacebook': typeof import("../components/icon/SocialFacebook.vue")['default']
    'LazyIconSocialFacebook2': typeof import("../components/icon/SocialFacebook2.vue")['default']
    'LazyIconSocialGoogle': typeof import("../components/icon/SocialGoogle.vue")['default']
    'LazyIconSocialGoogle2': typeof import("../components/icon/SocialGoogle2.vue")['default']
    'LazyIconSocialLine': typeof import("../components/icon/SocialLine.vue")['default']
    'LazyIconStatusBoxcheck': typeof import("../components/icon/StatusBoxcheck.vue")['default']
    'LazyIconStatusLoading': typeof import("../components/icon/StatusLoading.vue")['default']
    'LazyIconStatusShopFast': typeof import("../components/icon/StatusShopFast.vue")['default']
    'LazyIconStatusTimedelete': typeof import("../components/icon/StatusTimedelete.vue")['default']
    'LazyIconSuesccCheck': typeof import("../components/icon/SuesccCheck.vue")['default']
    'LazyIconTaxBill': typeof import("../components/icon/TaxBill.vue")['default']
    'LazyIconTrash': typeof import("../components/icon/Trash.vue")['default']
    'LazyIconTruckFast': typeof import("../components/icon/TruckFast.vue")['default']
    'LazyIconWarningInput': typeof import("../components/icon/WarningInput.vue")['default']
    'LazyIconWarrantys': typeof import("../components/icon/Warrantys.vue")['default']
    'LazyIconEyeHide': typeof import("../components/icon/eyeHide.vue")['default']
    'LazyIconEyeShow': typeof import("../components/icon/eyeShow.vue")['default']
    'LazyIconIPadProduct': typeof import("../components/icon/iPadProduct.vue")['default']
    'LazyIconVisa': typeof import("../components/icon/visa.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazySwiper': typeof import("../node_modules/swiper/swiper-vue")['Swiper']
    'LazySwiperSlide': typeof import("../node_modules/swiper/swiper-vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CardProduct: typeof import("../components/CardProduct.vue")['default']
export const CardProductFlashsale: typeof import("../components/CardProductFlashsale.vue")['default']
export const CardProductHome: typeof import("../components/CardProductHome.vue")['default']
export const CardProductRecommend: typeof import("../components/CardProductRecommend.vue")['default']
export const CompareMac: typeof import("../components/CompareMac.vue")['default']
export const CompareiPhone: typeof import("../components/CompareiPhone.vue")['default']
export const CradProductAccessories: typeof import("../components/CradProductAccessories.vue")['default']
export const Profile: typeof import("../components/Profile.vue")['default']
export const ProfileAddressProduct: typeof import("../components/ProfileAddressProduct.vue")['default']
export const ProfileOrderList: typeof import("../components/ProfileOrderList.vue")['default']
export const ServiceShipping: typeof import("../components/ServiceShipping.vue")['default']
export const ServiceWarranty: typeof import("../components/ServiceWarranty.vue")['default']
export const SwiperProductCategory: typeof import("../components/SwiperProductCategory.vue")['default']
export const SwiperProductHome: typeof import("../components/SwiperProductHome.vue")['default']
export const SwiperProductSerie: typeof import("../components/SwiperProductSerie.vue")['default']
export const IconAccount: typeof import("../components/icon/Account.vue")['default']
export const IconAddressProduct: typeof import("../components/icon/AddressProduct.vue")['default']
export const IconArrowDown: typeof import("../components/icon/ArrowDown.vue")['default']
export const IconArrowLeft: typeof import("../components/icon/ArrowLeft.vue")['default']
export const IconArrowRight: typeof import("../components/icon/ArrowRight.vue")['default']
export const IconBorderActive: typeof import("../components/icon/BorderActive.vue")['default']
export const IconBoxalt: typeof import("../components/icon/Boxalt.vue")['default']
export const IconBoxconfirm: typeof import("../components/icon/Boxconfirm.vue")['default']
export const IconCalendar: typeof import("../components/icon/Calendar.vue")['default']
export const IconCart: typeof import("../components/icon/Cart.vue")['default']
export const IconCheckCalendar: typeof import("../components/icon/CheckCalendar.vue")['default']
export const IconClock: typeof import("../components/icon/Clock.vue")['default']
export const IconCoupon: typeof import("../components/icon/Coupon.vue")['default']
export const IconCreditcard: typeof import("../components/icon/Creditcard.vue")['default']
export const IconDocument: typeof import("../components/icon/Document.vue")['default']
export const IconDots: typeof import("../components/icon/Dots.vue")['default']
export const IconHamburgerMenu: typeof import("../components/icon/HamburgerMenu.vue")['default']
export const IconInfo: typeof import("../components/icon/Info.vue")['default']
export const IconInvoiceState: typeof import("../components/icon/InvoiceState.vue")['default']
export const IconLocation: typeof import("../components/icon/Location.vue")['default']
export const IconLogout: typeof import("../components/icon/Logout.vue")['default']
export const IconOrderList: typeof import("../components/icon/OrderList.vue")['default']
export const IconPackage: typeof import("../components/icon/Package.vue")['default']
export const IconPeopleLogin: typeof import("../components/icon/PeopleLogin.vue")['default']
export const IconPlusAdd: typeof import("../components/icon/PlusAdd.vue")['default']
export const IconQuotation: typeof import("../components/icon/Quotation.vue")['default']
export const IconReceipt: typeof import("../components/icon/Receipt.vue")['default']
export const IconScan: typeof import("../components/icon/Scan.vue")['default']
export const IconSearch: typeof import("../components/icon/Search.vue")['default']
export const IconShipping: typeof import("../components/icon/Shipping.vue")['default']
export const IconShippingFast: typeof import("../components/icon/ShippingFast.vue")['default']
export const IconShoppingFast: typeof import("../components/icon/ShoppingFast.vue")['default']
export const IconSocialApple: typeof import("../components/icon/SocialApple.vue")['default']
export const IconSocialApple2: typeof import("../components/icon/SocialApple2.vue")['default']
export const IconSocialFacebook: typeof import("../components/icon/SocialFacebook.vue")['default']
export const IconSocialFacebook2: typeof import("../components/icon/SocialFacebook2.vue")['default']
export const IconSocialGoogle: typeof import("../components/icon/SocialGoogle.vue")['default']
export const IconSocialGoogle2: typeof import("../components/icon/SocialGoogle2.vue")['default']
export const IconSocialLine: typeof import("../components/icon/SocialLine.vue")['default']
export const IconStatusBoxcheck: typeof import("../components/icon/StatusBoxcheck.vue")['default']
export const IconStatusLoading: typeof import("../components/icon/StatusLoading.vue")['default']
export const IconStatusShopFast: typeof import("../components/icon/StatusShopFast.vue")['default']
export const IconStatusTimedelete: typeof import("../components/icon/StatusTimedelete.vue")['default']
export const IconSuesccCheck: typeof import("../components/icon/SuesccCheck.vue")['default']
export const IconTaxBill: typeof import("../components/icon/TaxBill.vue")['default']
export const IconTrash: typeof import("../components/icon/Trash.vue")['default']
export const IconTruckFast: typeof import("../components/icon/TruckFast.vue")['default']
export const IconWarningInput: typeof import("../components/icon/WarningInput.vue")['default']
export const IconWarrantys: typeof import("../components/icon/Warrantys.vue")['default']
export const IconEyeHide: typeof import("../components/icon/eyeHide.vue")['default']
export const IconEyeShow: typeof import("../components/icon/eyeShow.vue")['default']
export const IconIPadProduct: typeof import("../components/icon/iPadProduct.vue")['default']
export const IconVisa: typeof import("../components/icon/visa.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Swiper: typeof import("../node_modules/swiper/swiper-vue")['Swiper']
export const SwiperSlide: typeof import("../node_modules/swiper/swiper-vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCardProduct: typeof import("../components/CardProduct.vue")['default']
export const LazyCardProductFlashsale: typeof import("../components/CardProductFlashsale.vue")['default']
export const LazyCardProductHome: typeof import("../components/CardProductHome.vue")['default']
export const LazyCardProductRecommend: typeof import("../components/CardProductRecommend.vue")['default']
export const LazyCompareMac: typeof import("../components/CompareMac.vue")['default']
export const LazyCompareiPhone: typeof import("../components/CompareiPhone.vue")['default']
export const LazyCradProductAccessories: typeof import("../components/CradProductAccessories.vue")['default']
export const LazyProfile: typeof import("../components/Profile.vue")['default']
export const LazyProfileAddressProduct: typeof import("../components/ProfileAddressProduct.vue")['default']
export const LazyProfileOrderList: typeof import("../components/ProfileOrderList.vue")['default']
export const LazyServiceShipping: typeof import("../components/ServiceShipping.vue")['default']
export const LazyServiceWarranty: typeof import("../components/ServiceWarranty.vue")['default']
export const LazySwiperProductCategory: typeof import("../components/SwiperProductCategory.vue")['default']
export const LazySwiperProductHome: typeof import("../components/SwiperProductHome.vue")['default']
export const LazySwiperProductSerie: typeof import("../components/SwiperProductSerie.vue")['default']
export const LazyIconAccount: typeof import("../components/icon/Account.vue")['default']
export const LazyIconAddressProduct: typeof import("../components/icon/AddressProduct.vue")['default']
export const LazyIconArrowDown: typeof import("../components/icon/ArrowDown.vue")['default']
export const LazyIconArrowLeft: typeof import("../components/icon/ArrowLeft.vue")['default']
export const LazyIconArrowRight: typeof import("../components/icon/ArrowRight.vue")['default']
export const LazyIconBorderActive: typeof import("../components/icon/BorderActive.vue")['default']
export const LazyIconBoxalt: typeof import("../components/icon/Boxalt.vue")['default']
export const LazyIconBoxconfirm: typeof import("../components/icon/Boxconfirm.vue")['default']
export const LazyIconCalendar: typeof import("../components/icon/Calendar.vue")['default']
export const LazyIconCart: typeof import("../components/icon/Cart.vue")['default']
export const LazyIconCheckCalendar: typeof import("../components/icon/CheckCalendar.vue")['default']
export const LazyIconClock: typeof import("../components/icon/Clock.vue")['default']
export const LazyIconCoupon: typeof import("../components/icon/Coupon.vue")['default']
export const LazyIconCreditcard: typeof import("../components/icon/Creditcard.vue")['default']
export const LazyIconDocument: typeof import("../components/icon/Document.vue")['default']
export const LazyIconDots: typeof import("../components/icon/Dots.vue")['default']
export const LazyIconHamburgerMenu: typeof import("../components/icon/HamburgerMenu.vue")['default']
export const LazyIconInfo: typeof import("../components/icon/Info.vue")['default']
export const LazyIconInvoiceState: typeof import("../components/icon/InvoiceState.vue")['default']
export const LazyIconLocation: typeof import("../components/icon/Location.vue")['default']
export const LazyIconLogout: typeof import("../components/icon/Logout.vue")['default']
export const LazyIconOrderList: typeof import("../components/icon/OrderList.vue")['default']
export const LazyIconPackage: typeof import("../components/icon/Package.vue")['default']
export const LazyIconPeopleLogin: typeof import("../components/icon/PeopleLogin.vue")['default']
export const LazyIconPlusAdd: typeof import("../components/icon/PlusAdd.vue")['default']
export const LazyIconQuotation: typeof import("../components/icon/Quotation.vue")['default']
export const LazyIconReceipt: typeof import("../components/icon/Receipt.vue")['default']
export const LazyIconScan: typeof import("../components/icon/Scan.vue")['default']
export const LazyIconSearch: typeof import("../components/icon/Search.vue")['default']
export const LazyIconShipping: typeof import("../components/icon/Shipping.vue")['default']
export const LazyIconShippingFast: typeof import("../components/icon/ShippingFast.vue")['default']
export const LazyIconShoppingFast: typeof import("../components/icon/ShoppingFast.vue")['default']
export const LazyIconSocialApple: typeof import("../components/icon/SocialApple.vue")['default']
export const LazyIconSocialApple2: typeof import("../components/icon/SocialApple2.vue")['default']
export const LazyIconSocialFacebook: typeof import("../components/icon/SocialFacebook.vue")['default']
export const LazyIconSocialFacebook2: typeof import("../components/icon/SocialFacebook2.vue")['default']
export const LazyIconSocialGoogle: typeof import("../components/icon/SocialGoogle.vue")['default']
export const LazyIconSocialGoogle2: typeof import("../components/icon/SocialGoogle2.vue")['default']
export const LazyIconSocialLine: typeof import("../components/icon/SocialLine.vue")['default']
export const LazyIconStatusBoxcheck: typeof import("../components/icon/StatusBoxcheck.vue")['default']
export const LazyIconStatusLoading: typeof import("../components/icon/StatusLoading.vue")['default']
export const LazyIconStatusShopFast: typeof import("../components/icon/StatusShopFast.vue")['default']
export const LazyIconStatusTimedelete: typeof import("../components/icon/StatusTimedelete.vue")['default']
export const LazyIconSuesccCheck: typeof import("../components/icon/SuesccCheck.vue")['default']
export const LazyIconTaxBill: typeof import("../components/icon/TaxBill.vue")['default']
export const LazyIconTrash: typeof import("../components/icon/Trash.vue")['default']
export const LazyIconTruckFast: typeof import("../components/icon/TruckFast.vue")['default']
export const LazyIconWarningInput: typeof import("../components/icon/WarningInput.vue")['default']
export const LazyIconWarrantys: typeof import("../components/icon/Warrantys.vue")['default']
export const LazyIconEyeHide: typeof import("../components/icon/eyeHide.vue")['default']
export const LazyIconEyeShow: typeof import("../components/icon/eyeShow.vue")['default']
export const LazyIconIPadProduct: typeof import("../components/icon/iPadProduct.vue")['default']
export const LazyIconVisa: typeof import("../components/icon/visa.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazySwiper: typeof import("../node_modules/swiper/swiper-vue")['Swiper']
export const LazySwiperSlide: typeof import("../node_modules/swiper/swiper-vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
